### ISSUE TITLE
Fix asset list balance updating

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#110]
Asset list not updating on new block. Might make sense to query balances on every block to make sure they're up-to-date.

<img width="519" alt="Screenshot_2021-05-30_at_23 05 31" src="https://user-images.githubusercontent.com/332151/120203156-d9a38580-c240-11eb-9493-a4ec98c10bbe.png">

**Comment by clockworkgr** [comment]
Fixed in: https://github.com/tendermint/vue/pull/111

Will close when merged and published

**Comment by fadeev** [comment]
Fixed, apparently.
