### ISSUE TITLE
What the propose of master branch

### ISSUE THREAD

**Issue by shapkarin** [tendermint/vue#119]
It doesn't looks like `master` branch is maintainable.
The last update was at `20 Dec 2020` and the repo structure is much different with the `develop` branch.
The current develop branch is default and it's monorepo with several packages.

**Comment by marinhoarthur** [comment]
Hi @shapkarin!

We have been pretty busy lately. 

We'll do some house cleaning in the coming weeks (including `main` branch). Thanks for highlighting this!
