### ISSUE TITLE
Problem with prettier

### ISSUE THREAD

**Issue by Orijhins** [tendermint/vue#124]
When scaffolding the "blog" chain, the vue folder has a problem with prettier. When trying to compile, run or any other npm command, I get
```
Syntax Error: Thread Loader (Worker 0)
Failed to load config "prettier" to extend from.
Referenced from: /vue/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js
```

**Comment by Orijhins** [comment]
Oddly enough, it seems to compile with yarn...

**Comment by clockworkgr** [comment]
It should be ok with the updated deps merged in https://github.com/tendermint/vue/pull/123 (will be on the next release)

**Comment by Orijhins** [comment]
Great, thank you ! I'll close it once the release rolls out

**Comment by marinhoarthur** [comment]
Release is out, closing...
