### ISSUE TITLE
this.$store.getters.cosmos.staking.v1beta1/getParams is not a function

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#125]
> and somewhy keplr wallet connect does not work for me: 

```
TypeError: this.$store.getters.cosmos.staking.v1beta1/getParams is not a function
    at Proxy.<anonymous> (starport-vue.common.js:11007)
    at u (starport-vue.common.js:44537)
    at Generator._invoke (starport-vue.common.js:44767)
    at Generator.next (starport-vue.common.js:44592)
    at O (starport-vue.common.js:4311)
    at a (starport-vue.common.js:4333)
    at starport-vue.common.js:4340
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (starport-vue.common.js:4329)
    at Proxy.t (starport-vue.common.js:11095)
```

From Discord.

**Comment by clockworkgr** [comment]
`this.$store.getters['cosmos.staking.v1beta1/getParams'] ` iirc

**Comment by berelton** [comment]
![image](https://user-images.githubusercontent.com/93058200/138731539-396e5d64-c4e4-4c90-9f22-84b5775f8f83.png)

**Comment by marinhoarthur** [comment]
Hi @berelton 

Could you share a print of your `vue/src/store/generate` folder (i.e. the content of `generated`)?

**Comment by TrashCoder96** [comment]
Hello, i got the same errors. This is my generated folder:
[generated.zip](https://github.com/tendermint/vue/files/7414418/generated.zip)

index.ts
```
// THIS FILE IS GENERATED AUTOMATICALLY. DO NOT MODIFY.



export default { 
  
}


function load(mod, fullns) {
    return function init(store) {        
        if (store.hasModule([fullns])) {
            throw new Error('Duplicate module name detected: '+ fullns)
        }else{
            store.registerModule([fullns], mod)
            store.subscribe((mutation) => {
                if (mutation.type == 'common/env/INITIALIZE_WS_COMPLETE') {
                    store.dispatch(fullns+ '/init', null, {
                        root: true
                    })
                }
            })
        }
    }
}
```
package.json
```
{
  "name": "rr-bcp-core-js",
  "version": "0.1.0",
  "description": "Autogenerated cosmos modules vuex store",
  "author": "Starport Codegen <hello@tendermint.com>",  
  "license": "Apache-2.0",
  "licenses": [
    {
      "type": "Apache-2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  ],
  "main": "index.js",
  "publishConfig": {
    "access": "public"
  }
}
```

**Comment by clockworkgr** [comment]
@ilgooz @fadeev  it seems like the scaffolding clears the `store/generated/cosmos` folder downloaded along with the template and doesn't rebuild it

**Comment by berelton** [comment]
@marinhoarthur I have same content as @TrashCoder96 showed

do you have some temporary workaround?

**Comment by clockworkgr** [comment]
> @marinhoarthur I have same content as @TrashCoder96 showed
> 
> do you have some temporary workaround?

running `starport chain serve` with the `--proto-all-modules` flag may work I think

**Comment by berelton** [comment]
> > @marinhoarthur I have same content as @TrashCoder96 showed
> > do you have some temporary workaround?
> 
> running `starport chain serve` with the `--proto-all-modules` flag may work I think

this does not help :(

**Comment by marinhoarthur** [comment]
@berelton @TrashCoder96 we're currently investigating this and will post any updates here. 

FYI this is the root [issue](https://github.com/tendermint/starport/issues/1725).

I'll be following up this closely so that it's fixed asap.

**Comment by marinhoarthur** [comment]
There is a new [release](https://github.com/tendermint/starport/releases/tag/v0.18.2) patching this. Please [upgrade](https://docs.starport.com/guide/install.html#upgrading-your-starport-installation) your Starport to `v0.18.2`

Let us know how that works out.

@berelton @TrashCoder96
