### ISSUE TITLE
Consider removing node-sass

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#126]

**Comment by clockworkgr** [comment]
was removed in https://github.com/tendermint/vue/pull/123

**Comment by marinhoarthur** [comment]
Thanks @clockworkgr! 

Maybe we could even remove `sass` completely (do we really need it?). But let's leave this thread for another moment.

**Comment by clockworkgr** [comment]
> Thanks @clockworkgr!
> 
> Maybe we could even remove `sass` completely (do we really need it?). But let's leave this thread for another moment.

erm..yeah, we do :)
