### ISSUE TITLE
`invalid address: invalid Bech32 prefix` with custom prefix

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#127]
> Hi! I am trying to check the vue app for the blockchain, but I all the time getting "cosmos" prefix. How the .env file should look like to specify the prefix test?
http://localhost:1317/cosmos/bank/v1beta1/balances/cosmos1eqjyq025gwwh5xnzjyu27n68u8cepczkvvedv5

```json
{
  "code": 3,
  "message": "rpc error: code = InvalidArgument desc = invalid address: invalid Bech32 prefix; expected test, got cosmos: invalid request",
  "details": [
  ]
}
```

> my .env file:

```
VUE_APP_API_COSMOS=https://rest.alpha.starport.network
VUE_APP_WS_TENDERMINT=wss://rpc.alpha.starport.network/websocket
VUE_APP_API_TENDERMINT=https://rpc.alpha.starport.network
VUE_APP_ADDRESS_PREFIX=test
VUE_APP_CHAIN_ID=spn
VUE_APP_CHAIN_NAME="Test Network"
```

Question from Discord.

cc @marinhoarthur @Matthews3301

**Comment by berelton** [comment]
This is how I create the chain:

```
starport scaffold chain github.com/hello/planet --address-prefix test
```

**Comment by clockworkgr** [comment]
@berelton which starport version are you using?

also, it seems you copied `.env.spn` to `.env` and changed the address prefix

You should adjust the other variables in your own .env file as well.

Assuming the scaffolding command above (`starport scaffold chain github.com/hello/planet --address-prefix test`) and running `starport chain serve` in a local setup, your `.env` file should look like:

```
VUE_APP_API_COSMOS=http://localhost:1317
VUE_APP_WS_TENDERMINT=ws://localhost:26657/websocket
VUE_APP_API_TENDERMINT=http://localhost:26657
VUE_APP_ADDRESS_PREFIX=test
VUE_APP_CHAIN_ID=planet
VUE_APP_CHAIN_NAME="Planet Network"
```

**Comment by berelton** [comment]
thanks, that works!

But if I modify the name of token from `token` and `stake` to something similar to [this](https://github.com/zenchainprotocol/zenchain/blob/dev/config.yml), keplr wallet is unusable, I don't see any balance, cannot send it. From vue app it works fine.

Also I cannot find anything in doc how to "connect" the full value (like satoshi) to float value (like bitcoin). ANy reference to this?

> @berelton which starport version are you using?
> 
> also, it seems you copied `.env.spn` to `.env` and changed the address prefix
> 
> You should adjust the other variables in your own .env file as well.
> 
> Assuming the scaffolding command above (`starport scaffold chain github.com/hello/planet --address-prefix test`) and running `starport chain serve` in a local setup, your `.env` file should look like:
> 
> ```
> VUE_APP_API_COSMOS=http://localhost:1317
> VUE_APP_WS_TENDERMINT=ws://localhost:26657/websocket
> VUE_APP_API_TENDERMINT=http://localhost:26657
> VUE_APP_ADDRESS_PREFIX=test
> VUE_APP_CHAIN_ID=planet
> VUE_APP_CHAIN_NAME="Planet Network"
> ```

**Comment by berelton** [comment]
Also is there any documentation about how `config.yml` can look like, what params are expected?

**Comment by clockworkgr** [comment]
> thanks, that works!
> 
> But if I modify the name of token from `token` and `stake` to something similar to [this](https://github.com/zenchainprotocol/zenchain/blob/dev/config.yml), keplr wallet is unusable, I don't see any balance, cannot send it. From vue app it works fine.
> 
> Also I cannot find anything in doc how to "connect" the full value (like satoshi) to float value (like bitcoin). ANy reference to this?
> 
> > @berelton which starport version are you using?
> > also, it seems you copied `.env.spn` to `.env` and changed the address prefix
> > You should adjust the other variables in your own .env file as well.
> > Assuming the scaffolding command above (`starport scaffold chain github.com/hello/planet --address-prefix test`) and running `starport chain serve` in a local setup, your `.env` file should look like:
> > ```
> > VUE_APP_API_COSMOS=http://localhost:1317
> > VUE_APP_WS_TENDERMINT=ws://localhost:26657/websocket
> > VUE_APP_API_TENDERMINT=http://localhost:26657
> > VUE_APP_ADDRESS_PREFIX=test
> > VUE_APP_CHAIN_ID=planet
> > VUE_APP_CHAIN_NAME="Planet Network"
> > ```

When you first launch the frontend for  chain `planet` (or whatever you've named it) , when you try to connect to Keplr you should get a prompt to add chain `planet` to Keplr (using keplr's experimentalSuggestChain feature)

This includes information about the chain's denoms, staking denom, cointype , prefixes etc etc. (see relevant code here: https://github.com/tendermint/vue/blob/develop/packages/vue/src/components/SpWalletCreate/SpWalletCreate.vue#L306-L359)

However, if you subsequently change those parameters but the chain is still called `planet`, your Keplr instance will not overwrite those settings iirc which means it now has the wrong denoms etc.

So, you either give the chain a new chain id or open Keplr, click on the chain selector, select a chain other than `planet`, click on the chain selector again and click the X next to `planet` to remove it. You should then be able to suggest it again (this time with the correct params)

At least thats what I believe the issue is here

**Comment by clockworkgr** [comment]
> Also is there any documentation about how `config.yml` can look like, what params are expected?

that's a question for https://github.com/tendermint/starport, @ilgooz / @fadeev  ?

**Comment by berelton** [comment]
> > thanks, that works!
> > But if I modify the name of token from `token` and `stake` to something similar to [this](https://github.com/zenchainprotocol/zenchain/blob/dev/config.yml), keplr wallet is unusable, I don't see any balance, cannot send it. From vue app it works fine.
> > Also I cannot find anything in doc how to "connect" the full value (like satoshi) to float value (like bitcoin). ANy reference to this?
> > > @berelton which starport version are you using?
> > > also, it seems you copied `.env.spn` to `.env` and changed the address prefix
> > > You should adjust the other variables in your own .env file as well.
> > > Assuming the scaffolding command above (`starport scaffold chain github.com/hello/planet --address-prefix test`) and running `starport chain serve` in a local setup, your `.env` file should look like:
> > > ```
> > > VUE_APP_API_COSMOS=http://localhost:1317
> > > VUE_APP_WS_TENDERMINT=ws://localhost:26657/websocket
> > > VUE_APP_API_TENDERMINT=http://localhost:26657
> > > VUE_APP_ADDRESS_PREFIX=test
> > > VUE_APP_CHAIN_ID=planet
> > > VUE_APP_CHAIN_NAME="Planet Network"
> > > ```
> 
> When you first launch the frontend for chain `planet` (or whatever you've named it) , when you try to connect to Keplr you should get a prompt to add chain `planet` to Keplr (using keplr's experimentalSuggestChain feature)
> 
> This includes information about the chain's denoms, staking denom, cointype , prefixes etc etc. (see relevant code here: https://github.com/tendermint/vue/blob/develop/packages/vue/src/components/SpWalletCreate/SpWalletCreate.vue#L306-L359)
> 
> However, if you subsequently change those parameters but the chain is still called `planet`, your Keplr instance will not overwrite those settings iirc which means it now has the wrong denoms etc.
> 
> So, you either give the chain a new chain id or open Keplr, click on the chain selector, select a chain other than `planet`, click on the chain selector again and click the X next to `planet` to remove it. You should then be able to suggest it again (this time with the correct params)
> 
> At least thats what I believe the issue is here

Thanks! that was the issue. And How I can specify kepler to understand decimals?

**Comment by clockworkgr** [comment]
> > > thanks, that works!
> > > But if I modify the name of token from `token` and `stake` to something similar to [this](https://github.com/zenchainprotocol/zenchain/blob/dev/config.yml), keplr wallet is unusable, I don't see any balance, cannot send it. From vue app it works fine.
> > > Also I cannot find anything in doc how to "connect" the full value (like satoshi) to float value (like bitcoin). ANy reference to this?
> > > > @berelton which starport version are you using?
> > > > also, it seems you copied `.env.spn` to `.env` and changed the address prefix
> > > > You should adjust the other variables in your own .env file as well.
> > > > Assuming the scaffolding command above (`starport scaffold chain github.com/hello/planet --address-prefix test`) and running `starport chain serve` in a local setup, your `.env` file should look like:
> > > > ```
> > > > VUE_APP_API_COSMOS=http://localhost:1317
> > > > VUE_APP_WS_TENDERMINT=ws://localhost:26657/websocket
> > > > VUE_APP_API_TENDERMINT=http://localhost:26657
> > > > VUE_APP_ADDRESS_PREFIX=test
> > > > VUE_APP_CHAIN_ID=planet
> > > > VUE_APP_CHAIN_NAME="Planet Network"
> > > > ```
> > 
> > 
> > When you first launch the frontend for chain `planet` (or whatever you've named it) , when you try to connect to Keplr you should get a prompt to add chain `planet` to Keplr (using keplr's experimentalSuggestChain feature)
> > This includes information about the chain's denoms, staking denom, cointype , prefixes etc etc. (see relevant code here: https://github.com/tendermint/vue/blob/develop/packages/vue/src/components/SpWalletCreate/SpWalletCreate.vue#L306-L359)
> > However, if you subsequently change those parameters but the chain is still called `planet`, your Keplr instance will not overwrite those settings iirc which means it now has the wrong denoms etc.
> > So, you either give the chain a new chain id or open Keplr, click on the chain selector, select a chain other than `planet`, click on the chain selector again and click the X next to `planet` to remove it. You should then be able to suggest it again (this time with the correct params)
> > At least thats what I believe the issue is here
> 
> Thanks! that was the issue. And How I can specify kepler to understand decimals?

that's actually a client/display issue...as far as the chain is concerned, only the base_denom exists..

You need to modify the call to experimentalSuggestChain. 

You can call it somewhere else in your frontend prior to the call by SpWalletCreate above so it doesnt get overwritten.

Note the following lines: 

https://github.com/tendermint/vue/blob/develop/packages/vue/src/components/SpWalletCreate/SpWalletCreate.vue#L312-L314
https://github.com/tendermint/vue/blob/develop/packages/vue/src/components/SpWalletCreate/SpWalletCreate.vue#L335-L338
https://github.com/tendermint/vue/blob/develop/packages/vue/src/components/SpWalletCreate/SpWalletCreate.vue#L348-L350

In your case, assuming 1000000uzen = 1 ZEN (i.e. precision of 6)
coinDenom would be ZEN
coinMinimalDenom would be uzen
and coinDecimals = 6

**Comment by fadeev** [comment]
@berelton 

> Also is there any documentation about how config.yml can look like, what params are expected?

https://docs.starport.com/kb/config.html
