### ISSUE TITLE
feat: general purpose modal component with an overlay

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#137]
<img width="504" alt="Screenshot 2021-11-30 at 12 49 49" src="https://user-images.githubusercontent.com/332151/144024691-7639ba90-316f-42fc-b2d7-54bff5e48afa.png">

<img width="525" alt="Screenshot 2021-11-30 at 12 51 05" src="https://user-images.githubusercontent.com/332151/144024695-4a84e924-7716-40a4-be0e-1e9590f1770e.png">

**Comment by Matthews3301** [comment]
https://github.com/tendermint/vue/pull/143
