### ISSUE TITLE
`transpileDependencies` config should be an array 

### ISSUE THREAD

**Issue by marinhoarthur** [tendermint/vue#141]
According to the [reference](https://cli.vuejs.org/config/#transpiledependencies), this property should have an array assigned to it and not a boolean as in [here](https://github.com/tendermint/vue/blob/737a3d31d450e7a969fc64fb14d289d09835e2b1/packages/vue/vue.config.js#L5) and [here](https://github.com/tendermint/vue/blob/737a3d31d450e7a969fc64fb14d289d09835e2b1/packages/template/vue.config.js#L5)

**Comment by marinhoarthur** [comment]
This should do the trick:

```
module.exports = {
  transpileDependencies: ['@starport/client-js']
}
```

Let's test and release a patch!

**Comment by 0xkaranchauhan** [comment]
I tried downgrading node to v16.13.1.
Then removed and scaffolded the checker's file again.
