### ISSUE TITLE
Frontend ibc relayer problem

### ISSUE THREAD

**Issue by vincadian** [tendermint/vue#146]
**Describe the bug**
Front end ibc relayer is not working. 
![image](https://user-images.githubusercontent.com/79286362/144872827-6cd39b8f-1f79-4ac8-87b2-a925ae391d45.png)
![image](https://user-images.githubusercontent.com/79286362/144873380-160bcfc2-ca42-48f7-8289-0135464dfb02.png)

**To Reproduce**
1. Starport chain serve
2. Import Monorepo vue
3. Serve the template folder 

**Please provide the version output**
 - `starport version`: 44.1

**Comment by vincadian** [comment]
Hi, is there some news concerning this bug

**Comment by marinhoarthur** [comment]
I'm currently investigating it

**Comment by clockworkgr** [comment]
@vincadian is it possible you had a wallet created/stored in your browser from an earlier version of starport?

Can you nuke localStorage for the served template and try again with a newly created/imported account?

**Comment by vincadian** [comment]
ok now I have this 
![image](https://user-images.githubusercontent.com/79286362/146572516-34aadc57-ce84-4382-aa6f-88f519f9fdbb.png)

**Comment by vincadian** [comment]
![image](https://user-images.githubusercontent.com/79286362/146572675-794de221-2aed-4f8b-8550-0f2c51e3ab4a.png)

**Comment by vincadian** [comment]
![image](https://user-images.githubusercontent.com/79286362/146612715-a2b80d10-45ad-4e0d-a355-249f01cc8ab5.png)

**Comment by vincadian** [comment]
![image](https://user-images.githubusercontent.com/79286362/146612762-b1dbf8bf-fd18-461b-9c13-fbb7e3db3c6c.png)

**Comment by vincadian** [comment]
The problem is only for kepler wallet
