### ISSUE TITLE
address not being updated on keplr account change

### ISSUE THREAD

**Issue by marinhoarthur** [tendermint/vue#151]
Steps to reproduce:

1. Connect to Keplr
2. Open Keplr and switch account 
3. Open our Wallet. The addresses do not match anymore (one from previous account, the other one from the current)

![Screen Shot 2021-12-09 at 09 31 49](https://user-images.githubusercontent.com/3693700/145397276-a9e69044-faf6-472c-bf92-619a1695f52f.png)

**Comment by clockworkgr** [comment]
```
window.addEventListener('keplr_keystorechange', async () => { ...} );
```
use that but @starport/vuex `common/wallet` also needs updating as it stores the first instance  and needs to be updated (or refactored to always query the currently  connected keplr)

**Comment by marinhoarthur** [comment]
update: 

- will be closed once next major is published
