### ISSUE TITLE
unable to suggest new chain if wallet is locked

### ISSUE THREAD

**Issue by marinhoarthur** [tendermint/vue#154]
Steps:

- chain `mars`:
-- Connect to Keplr
-- Refresh the page (so to get the wallet in "locked mode")
- chain `neptune`
-- Using the same browser, try to unlock the wallet

![Screenshot from 2021-12-15 14-01-13](https://user-images.githubusercontent.com/3693700/146231086-d39bd123-f874-47ad-ab1f-99a7ac14f4ee.png)

**Comment by clockworkgr** [comment]
why is the chain suddenly different?

**Comment by marinhoarthur** [comment]
In this case because multiples chain were served on the same hostname (localhost)... 

But the thing is, our wallet only unlocks if running chain was already added to Keplr. Don't know if this is necessary...

**Comment by marinhoarthur** [comment]
update: 

- will be closed once next major is published
