### ISSUE TITLE
fix(ui): loading state shows up when switching between tabs (assets)

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#204]
To reproduce:

* sign in with an account
* click on the "Data" tab
* click on the "Portfolio" tab

<img width="1323" alt="Screenshot 2022-02-17 at 14 32 00" src="https://user-images.githubusercontent.com/332151/154473044-5d0b0776-074b-4218-9c19-6b1e3bc6e876.png">

**Comment by mihailmarcu** [comment]
@fadeev, @marinhoarthur,
Is this issue related to what we discussed regarding reloading components when changing a router? I wonder if solution can be in one task. Wdyt?

**Comment by marinhoarthur** [comment]
For now let's fix skeleton-forever. Soon enough we will be refactoring overall fetching of data.
