### ISSUE TITLE
fix(ui): wallet settings has no way to return to overview

### ISSUE THREAD

**Issue by mikeeus** [tendermint/vue#248]
To reproduce:
- Connect wallet
- Open wallet
- Click on "Settings"
- There's no way to back to overview. And reopening the wallet shows the settings.

![image](https://user-images.githubusercontent.com/16954412/155336384-548249df-9d8e-423c-b1a7-fd04269e50eb.png)

![image](https://user-images.githubusercontent.com/16954412/155336174-a33b3997-d596-41ea-90f0-b60284c7495d.png)

**Comment by mihailmarcu** [comment]
Hi @mikeeus,
Thanks for your time to explore around the development. We have already fixed and are preparing a patch for. 

If you don't mind, I'll close the issue.

Duplicates #200
