### ISSUE TITLE
js-ipfs

### ISSUE THREAD

**Issue by faddat** [tendermint/vue#29]
**js-ipfs**

Is a fairly weighty browser-based "ipfs node in your web browser".

I've played with it some and I think it is decent/stable.  Basically in our context I'd want to use it to be able to retrieve CIDs stored in -- just for example:

```
starport type post title body image
```

where image contains a cid

It would probably end up in these places:

https://github.com/tendermint/vue/blob/develop/package.json

And then in a component as well, and maybe in another place, go import it.

Learning question: Vue components are bits that contain html, css and js in a single file.  But this isn't the right place to import js-ipfs, right?  do that "above" the component?

Lastly, while I am pretty pumped about addding js-ipfs, largely for:

* images / video / audio
* pubsub
* CRDTs

Is js-ipfs too heavy for inclusion, if we can't make it so that it's only loaded when that component is in use?  

For now, I figure "that component" is a blog or blog + image viewer.

Likely many interesting use cases though.

**Comment by fadeev** [comment]
> Vue components are bits that contain html, css and js in a single file. But this isn't the right place to import js-ipfs, right? do that "above" the component?

Most likely `js-ipfs` should be imported inside the component that uses it OR if `js-ipfs` deals with fetching/sending data, then inside a Vuex store.

**Comment by fadeev** [comment]
I think this is a bit out of scope of Starport Interface.
