### ISSUE TITLE
Error on querying unsuccessful tx

### ISSUE THREAD

**Issue by vince19972** [tendermint/vue#30]
Note: This is not an issue resolvable in this repo. It's just documented here for further discussion. 

### Description
A failed tx can't be found in the chain in Stargate version.

![Screen Shot 2020-11-09 at 2 51 32 PM](https://user-images.githubusercontent.com/14227221/98608067-73f9a700-22b8-11eb-85c7-9548651c9712.png)

### Details

**Cmd used to create tx**
```
{app}d tx bank send {addr 1} {addr 2} 10token --from=user1 --keyring-backend test --chain-id {app} --account-number 0 --fees 100000token
```
**Returned result after tx created**
```
{"height":"0","txhash":"3396E19225B0E275AA0AEFF09E8C3488DDFF615134AF41B1E8C3F67C726DEEEB","codespace":"sdk","code":5,"data":"","raw_log":"1000token is smaller than 100000token: insufficient funds: insufficient funds","logs":[],"info":"","gas_wanted":"200000","gas_used":"25241","tx":null,"timestamp":""}
```

**Cmd used to get tx**
```
bard q tx 3396E19225B0E275AA0AEFF09E8C3488DDFF615134AF41B1E8C3F67C726DEEEB
```

**Returned error**
```
Error: RPC error -32603 - Internal error: tx (3396E19225B0E275AA0AEFF09E8C3488DDFF615134AF41B1E8C3F67C726DEEEB) not found
```

**Comment by fadeev** [comment]
That's the correct behavior that can be observed both on Launchpad and Stargate.

When tx fails due to lack of funds (when a user sends more than they have), tx is registered on-chain. When tx fails due to "insufficient funds" for fees, it fails a "basic check" and is not included in the block.

**Comment by vince19972** [comment]
@fadeev I see. But in Launchpad, after a failed tx is created, you can query it with tx hash, and getting this response:

```
{
  "height": "34",
  "txhash": "1E7C7AAD1BB6ED73EEFE4695CB01C3BD6C4C917F1A91CD316ADC4B800363B7FB",
  "codespace": "sdk",
  "code": 5,
  "raw_log": "insufficient funds: insufficient account funds; 1000token \u003c 1000000token: failed to execute message; message index: 0",
  "gas_wanted": "10000000",
  "gas_used": "36258",
  "tx": {
    "type": "cosmos-sdk/StdTx",
    "value": {
      "msg": [
        {
          "type": "cosmos-sdk/MsgSend",
          "value": {
            "from_address": "cosmos1dj5ujle6e6ehsual67jgmkp3cqmv4uauk6vhwg",
            "to_address": "cosmos1dj5ujle6e6ehsual67jgmkp3cqmv4uauk6vhwg",
            "amount": [
              {
                "denom": "token",
                "amount": "1000000"
              }
            ]
          }
        }
      ],
      "fee": {
        "amount": [],
        "gas": "10000000"
      },
      "signatures": [
        {
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "AqpG/uXiR8hjsMDxDay/Fb9iYpL/iuT3usufzxrPbCo1"
          },
          "signature": "dgONcR3RbAiP+j8c0lRuoXmGHsjD9r3lyOgRPXDj/usOyw+ksmLA1K+bFZdBH+WkM8g5MJ2BtCuNfY73lkkvyA=="
        }
      ],
      "memo": ""
    }
  },
  "timestamp": "2020-11-10T12:59:06Z"
}
```

This is why block explorers can display failed txs, I suppose? Without the ability to query it, we can't display the failed ones.

**Comment by fadeev** [comment]
@vince19972 here is a failed tx on Stargate. It's possible to query for this tx, because it has failed due to a lack of funds for transfer. If it had failed due to a lack of funds _for fees_, it wouldn't have been possible to query for it.

<img width="1529" alt="Screenshot 2020-11-10 at 18 22 47" src="https://user-images.githubusercontent.com/332151/98679392-c226ad00-2381-11eb-809b-2a024321bf0b.png">

**Comment by vince19972** [comment]
@fadeev Ahhh I see. Thanks for clearing up 🙏
