### ISSUE TITLE
Tendermint version number missing

### ISSUE THREAD

**Issue by vince19972** [tendermint/vue#38]
### Brief Description

Tendermint version number is missing from `:26657/status` response, which is raised as [an issue here](https://github.com/cosmos/cosmos-sdk/issues/7963). This blocks the `signAndBroadcast` function in `@cosmjs/stargate` from working properly. From the [comment in the source code](https://github.com/cosmos/cosmjs/blob/master/packages/tendermint-rpc/src/v0-33/responses.ts#L505), I think cosmjs team is aware of the issue too. 

### Temp workaround for testing 

Although it's not working yet, for testing purpose on Scaffold UI [on this branch](https://github.com/tendermint/vue/tree/vince19972/scaffold-stargate), I made local revisions in `node_modules` to workaround it. 

In file `tendermint-rpc/build/adaptorforversion.js`, this revision was made:
```
function adaptorForVersion(version) {
    // if (version.startsWith("0.33.") || version.startsWith("0.34.") || hashes.v0_34.includes(version)) {
        return v0_33_1.v0_33;
    // }
    // else {
    //     throw new Error(`Unsupported tendermint version: ${version}`);
    // }
}
```

And in file `tendermint-rpc/build/v0-33/responses.js`, changing line 217 from `version: encodings_1.assertNotEmpty(data.version)` to `version: encodings_1.assertNotEmpty('0.33')` does the trick.

### Note 

This is by no means solution for the problem, but rough testing for tx creating. This issue can be closed when SDK and cosmjs team solves the issue.

**Comment by webmaster128** [comment]
We added this dirty hack, which became necessary when changing the backend from rc2 to rc3: https://github.com/cosmos/cosmjs/pull/536/commits/ae1f2e28a0da44e6a9f8c448465e26997c69d107

**Comment by vince19972** [comment]
Thanks @webmaster128! I'll upgrade the package and give it a try later.

**Comment by webmaster128** [comment]
This is not yet released. Can create a release for you if it helps.

**Comment by webmaster128** [comment]
Published 0.24.0-alpha.8 now, which includes the workaround necessary to connect to rc3.

**Comment by vince19972** [comment]
@webmaster128 it's working! Thanks for helping out!

**Comment by webmaster128** [comment]
@vince19972 my pleasure, enjoy

**Comment by fadeev** [comment]
Pretty sure this is no longer relevant.

**Comment by webmaster128** [comment]
Right. CosmJS now has a Tendermint34Client which avoids the unreliable Tendermint version check. This is used in all higher level Stargate clients.
