### ISSUE TITLE
Account number affects tx creation

### ISSUE THREAD

**Issue by vince19972** [tendermint/vue#39]
### Short Description 

An account with `account_number: 0` can't create a tx. On the other hand, account with  `account_number: 1` creates a tx without a problem.

### Environment 

This issue was found while creating a tx by using `SignAndBroadcast` function from CosmJS ([v0.24.0-alpha.8](https://github.com/cosmos/cosmjs/releases/tag/v0.24.0-alpha.8)) in a chain generated by `Starport`. To replicate the issue, you'll need to:

1. Install Starport [from source](https://github.com/tendermint/starport)
2. Clone the frontend interface from [this branch](https://github.com/tendermint/vue/tree/vince19972/scaffold-stargate), which is capable of interacting with Stargate, and using the latest version of CosmJS to create txs
3. [Build a chain](https://github.com/tendermint/starport/blob/develop/docs/1%20Introduction/3%20Quickstart.md) with Starport and run it
4. Run the frontend app (`npm i` and `npm run serve`), which should be opened at `localhost:8080`
5. On the frontend interface, log in with the first mnemonic provided by `Starport` cli, and send a token to another account

![Screen Shot 2020-11-17 at 3 10 11 PM](https://user-images.githubusercontent.com/14227221/99448832-9bbac180-28ed-11eb-8557-e1db7b6b2fc0.png)

### Notes

- The action of token sending is dispatched [over here](https://github.com/tendermint/vue/blob/vince19972/scaffold-stargate/src/store/bank.js#L15) on the frontend
- Only creating tx from `account_number: 0` fails
- It's confirmed that `account_number` is fetched correctly through API endpoint (`localhost:1317/cosmos/auth/v1beta1/accounts/{address}`)

**Comment by vince19972** [comment]
@ilgooz @ltacker @fadeev 👆

**Comment by fadeev** [comment]
I'd need to look more into the first issue, as for the second: balances are consistent, because stake has been, well, staked by this account with a validation. Basically, all of these tokens were deposited to a validator.

**Comment by fadeev** [comment]
No longer relevant.
