### ISSUE TITLE
Unregistered type url: undefined

### ISSUE THREAD

**Issue by emperorjm** [tendermint/vue#46]
I have the Cosmos SDK v0.39.2 working perfectly but now am testing out the Stargate version of Cosmos SDK 0.40.0-rc3 using tendermint/vue v0.1.12 in my frontend app but I am receiving the following error when trying to execute a REST API route to create a new Type:

```
Error: Unregistered type url: undefined
    at Registry.lookupTypeWithError (registry.js?4250:29)
    at Registry.encode (registry.js?4250:37)
    at eval (registry.js?4250:45)
    at Array.map (<anonymous>)
    at Registry.encodeTxBody (registry.js?4250:44)
    at Registry.encode (registry.js?4250:35)
    at SigningStargateClient.signAndBroadcast (signingstargateclient.js?172a:59)
```

The API route is called using the following:

`axios.post(API + '/financingcompany/financing_accounts', req).then(async response => {`

The following response is received:

```
type: "financingcompany/CreateFinancingAccount"
value:
companyAddress: "128 Prinsep St"
companyName: "Test Comp Ltd"
companyNumber: "875897t98"
country: "AE"
creator: "comos1ap6kmlgv77k6lc65nkjl8vmal9msqzzdskgyvk"
emailAddress: "test1@gmail.com"
phoneNumber: "25252242432"
processingFee: "123"
websiteAddress: "http://google.com"
```

**Comment by fadeev** [comment]
In Stargate browser-chain interactions work differently. Here is an example of how to do it manually:

https://gist.github.com/fadeev/a4981eff1cf3a805ef10e25313d5f2b7

**Comment by emperorjm** [comment]
Thanks a lot, the code snippet works. Had to make sure the RPC service was setup as well within the backend.
