### ISSUE TITLE
Best way to deal with Error Handling

### ISSUE THREAD

**Issue by emperorjm** [tendermint/vue#47]
Within Stargate (gRPC) and Launchpad (REST) I realize that when an error is thrown a 200 success HTTP code is returned which doesn't seem to be standard practice when an error is thrown.

Within the result set I realize that a **code** is returned but I am unable to find where these codes are defined. Within Launchpad I do realize that when the error is returned from the Handler the error code returned is not set to 200 (could be 500, 404 etc) within the BasicValidator this is not the case as a 200 code is returned.

What's the standard way of dealing with error handling on the frontend?

**Comment by fadeev** [comment]
`code` within response body is returned by Tendermint and the only hard-coded value is `0`, which corresponds to `OK`:

https://docs.tendermint.com/master/spec/abci/abci.html#errors

Everything else is application-specific.

I would also like to welcome you to our developer chat, where you would be able to get answers from the larger Cosmos community: https://discord.gg/vcExX9T Issues are more for bugs and feature requests 🙂

**Comment by emperorjm** [comment]
Thanks for the clarification. As suggested, I'll will take all new non-bug related queries to the discord channel.
