### ISSUE TITLE
modules: fix generic components

### ISSUE THREAD

**Issue by ilgooz** [tendermint/vue#51]
Here is a list of components that needs to be fixed in order to get compatible with code vuex generation:

- [x] `chain/` and variants cannot be assumed to be exists for every module. A different path can be configred by Starport or user in `config.yml`: https://github.com/tendermint/vue/blob/db8466780ca799a6de215e94da789cc3a7ecb6e2/packages/vue/src/components/SpTypeForm/SpTypeForm.vue#L132 
- [x] `Query` cannot be assumed to be exists for every module: https://github.com/tendermint/vue/blob/db8466780ca799a6de215e94da789cc3a7ecb6e2/packages/vue/src/components/SpTypeForm/SpTypeForm.vue#L132 
- [x] `MsgCreate`  and variants cannot be assumed to be exists for every module: https://github.com/tendermint/vue/blob/db8466780ca799a6de215e94da789cc3a7ecb6e2/packages/vue/src/components/SpTypeForm/SpTypeForm.vue#L215
- [x] `All` cannot be assumed to be exists for every module: https://github.com/tendermint/vue/blob/db8466780ca799a6de215e94da789cc3a7ecb6e2/packages/vue/src/components/SpTypeList/SpTypeList.vue#L62
- [x] `/Query`  cannot be assumed to be exists for every module: https://github.com/tendermint/vue/blob/db8466780ca799a6de215e94da789cc3a7ecb6e2/packages/vue/src/components/SpTypeList/SpTypeList.vue#L90
- [ ] ...?

**Comment by clockworkgr** [comment]
As discussed, type form / type list components are for starport-scaffolded CRUD types only at this time which do include all of the above.
