### ISSUE TITLE
Issue with VUE_APP_CUSTOM_URL

### ISSUE THREAD

**Issue by ft-thor** [tendermint/vue#52]
There is an issue with VUE_APP_CUSTOM_URL, instead of reading from .env file it always set to localhost:12345.
The SpBlockExplorer isn't working with live domain, it works with the localhost:12345 only

Please check the code.

https://github.com/tendermint/vue/blob/2e84ecf851d8ef21c850166ea1293cefa74bee64/src/store/env.js#L33

**Comment by fadeev** [comment]
The structure of the Vuex store has changed since then. We still need to sort out where API endpoints should come from (`.env`, env variables, etc.). We'll create a new issue for that.
