### ISSUE TITLE
Changing address prefix doesn't work

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#56]
```js
    await this.$store.dispatch("common/env/init", {
      prefix: "foo",
    });
```

Still shows `cosmos` in UI.

**Comment by clockworkgr** [comment]
a) it's addrPrefix
b) If you're using the starport module (default) , it reconfigures itself for nodes from the :12345/status endpoint and also picks up prefix from the env variables set by starport: VUE_APP_ADDRESS_PREFIX

**Comment by fadeev** [comment]
Yes, my mistake, used `addrPrefix`, still can't see the change.

**Comment by clockworkgr** [comment]
Does starport set VUE_APP_ADDRESS_PREFIX properly? can you comment out starport(store) from config.js and try again?

**Comment by clockworkgr** [comment]
ah....spotted it, fixed in: https://github.com/tendermint/vue/commit/4c6ffd37c3b84b0b7a57299832496f2c56961089

**Comment by fadeev** [comment]
@clockworkgr on `@starport/vue` `0.1.32` the prefix now doesn't get added at all. Can't seem to be able to use the app. `0.1.31` looks fine.

<img width="803" alt="Screenshot 2021-03-20 at 21 29 02" src="https://user-images.githubusercontent.com/332151/111877097-776a1100-89c3-11eb-833b-0c074c026bda.png">

**Comment by clockworkgr** [comment]
Fixed in https://github.com/tendermint/vue/tree/v0.1.37
