### ISSUE TITLE
Move away from using `:12345/status` endpoint

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#66]
Data should be fetched from publicly accessible APIs, like 1317, 26657, etc.

**Comment by clockworkgr** [comment]
should we retire this from the vue components regardless of when we retire the endpoint altogether?

**Comment by fadeev** [comment]
Yes, I think we can remove it from our Vue/Vuex components first and then disable it in Starport.

**Comment by clockworkgr** [comment]
ok...suits me just fine ...it was annoying to handle :)

**Comment by clockworkgr** [comment]
Done in: https://github.com/tendermint/vue/pull/64/commits/70802681c92107cfe6848e6cfd20ed6c57e2b919
