### ISSUE TITLE
style: remove horizontal bar, when account dropdown is collapsed

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#69]
<img width="739" alt="Screenshot 2021-03-31 at 23 53 04" src="https://user-images.githubusercontent.com/332151/113195976-5e434900-927c-11eb-8c93-18058d844fc8.png">

**Comment by clockworkgr** [comment]
fixed in https://github.com/tendermint/vue/pull/64/commits/47c49e29367a290d7a71f14611ecf2e6a2a867ab
