### ISSUE TITLE
Edit and delete in the UI

### ISSUE THREAD

**Issue by lukitsbrian** [tendermint/vue#7]
Enable editing and deleting items in the UI.

Editing could redirect to a separate page/open a modal/replace the content with the JSON text field, similar to what exists for creating a field.
Deleting could have an `x` in the corner and once clicked, pops up a confirmation modal that asks "Are you sure you want to delete this item?"

**Comment by clockworkgr** [comment]
No longer relevant (and new UI does have edit/delete modals)
