### ISSUE TITLE
Find a better way to test PRs

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#70]
Right now for me to test out PRs I need to fetch, npm link, scaffold, etc. Having a version of the frontend deployed somewhere like Netlify with one click to preview from PR would be a timesaver.

**Comment by clockworkgr** [comment]
Yeah it's annoying....let me think of a way to automate it....It doesn't help that the PRs to test are usually tied to a tendermint/starport PR as well

**Comment by clockworkgr** [comment]
Will probably be handled by https://github.com/tendermint/starport/issues/943 for now

**Comment by clockworkgr** [comment]
Completed in https://github.com/tendermint/starport/pull/944
