### ISSUE TITLE
Small fixes here and there

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#71]
- [x] Prevent user from deleting last token. This shouldn't happen:

<img width="705" alt="Screenshot 2021-04-02 at 14 08 34" src="https://user-images.githubusercontent.com/332151/113401565-02cca480-93bd-11eb-853f-93ffea945c3a.png">

- [x] Add a shadow to the hamburger circle button
- [x] Try sending tokens when the backend is not available (or becomes unavailable). Send tokens button spins forever, should somehow revert to original state if send was unsuccessful.

**Comment by clockworkgr** [comment]
https://github.com/tendermint/vue/pull/64/commits/284fc671b05d637cb18830705dd580833f31ce9f

https://github.com/tendermint/vue/pull/64/commits/b98317c4eef65bc739a25e684736076c662ae02e

https://github.com/tendermint/vue/pull/64/commits/ca296d0ce64d78ba031e400e22fbc5eb5c6f4411

:)

**Comment by fadeev** [comment]
- [x] prevent users from adding the same denom endlessly (in this case a user only has `10token` in total)

<img width="658" alt="Screenshot 2021-04-02 at 15 12 21" src="https://user-images.githubusercontent.com/332151/113407057-057fc780-93c6-11eb-9add-60bf50e4357f.png">

- [x] disable button, unless the form looks like it can be submitted (basic validation): address should be there, token values should be numbers, etc.
- [x] make `0` in input as a placeholder. Right now a user has to manually remove the zero, and input a value.

**Comment by clockworkgr** [comment]
1 and 3 done in https://github.com/tendermint/vue/pull/64/commits/d47309cd3eeb3c6b2152b7017bbd07d35572e900

**Comment by clockworkgr** [comment]
2 done on https://github.com/tendermint/vue/pull/64/commits/1dd36a3ee499f43972fac572d113402ba0241cea

(if this is ok as well I'll go ahead and merge that PR)

**Comment by fadeev** [comment]
@clockworkgr For some reason, it prevents me from sending tokens. On `master`, on GP.

<img width="1589" alt="Screenshot 2021-04-02 at 19 33 22" src="https://user-images.githubusercontent.com/332151/113425638-ab91f880-93eb-11eb-9640-d1be5f158c4a.png">

Maybe it's just me, but could you try going through the process yourself to see if it works properly? Creating a chain, signing in with Alice's account, sending tokens to Bob, etc.

**Comment by clockworkgr** [comment]
Does sending fail? Or is the button actually disabled?

**Comment by clockworkgr** [comment]
fixed in https://github.com/tendermint/vue/pull/64/commits/d781745ab98a4d52ae793706a608bc7aba6ac835
