### ISSUE TITLE
View transactions sent to my own address

### ISSUE THREAD

**Issue by 0xb4rt** [tendermint/vue#75]
**Expected Behavior**

Maybe display a new "status" for these cases or just one of them (`Sent` or `Received`).

**Actual Behavior**

![Captura de Tela 2021-04-04 às 16 12 55](https://user-images.githubusercontent.com/68613335/113519928-eae45480-9565-11eb-851f-16f7ad4f335e.png)

**Comment by fadeev** [comment]
@0xb4rt good catch! Yes, if a user sends to themselves, we may need to show transaction rows: both "Sent to" and "Received from".

**Comment by marinhoarthur** [comment]
update: 

- can be solved by adjusting [this if](https://github.com/tendermint/vue/blob/c2d6d4fa6ee7b738342b30d5848dae6a88dcab85/packages/vue/src/components/SpTransferList/SpTransferList.vue#L256-L264) and others alike but IMO let's use next major for that (i.e. solve using next implementation)



cc @Matthews3301 let's be aware of this behavior while refactoring the tx list
