### ISSUE TITLE
Use sha256 from @cosmjs/crypto

### ISSUE THREAD

**Issue by webmaster128** [tendermint/vue#78]
There are two places where `sha256` is used:

```js
let txHash = sha256(Buffer.from(tx));
```

and

```js
const txHash = sha256(Buffer.from(encodedTx, 'base64'))
```

Both can be replaces with `import { sha256 } from "@cosmjs/crypto";`:

```js
import { sha256 } from "@cosmjs/crypto";

// ..

let txHash = sha256(tx);
```

and

```js
import { sha256 } from "@cosmjs/crypto";
import { fromBase64 } from "@cosmjs/encoding";

// ..

const txHash = sha256(fromBase64(encodedTx))
```

which has a few advantages:

- Less dependencies because @cosmjs/crypto is in the dependency tree anyways (js-sha256 was updated in 2017)
- No need for Buffer inputs (which is not really a JS type but a Node.js type)
- The resulting hash is an Uint8Array not hex, which works better as input in many CosmJS APIs (like `hash: fromHexString(txHash),` becomes `hash: txHash,`). If you need hex, there is `import { toHex } from "@cosmjs/encoding"`
- ~You can easily migrate to the class `Sha256`, which supports incremental hashing~ Update: good but not better because js-sha256 can do this too.
- Type support (for IDE users and future TypeScript development)

**Comment by clockworkgr** [comment]
Thanks for the heads up. A lot of the code re: relaying as well as other parts was written with a  tight deadline to get something working so needs some polish.  Been refactoring stuff  for a couple of days now including porting the component library over to TS so will def be taking your suggestions.

**Comment by clockworkgr** [comment]
Done in https://github.com/tendermint/vue/tree/v0.1.44
