### ISSUE TITLE
Investigate switching to vite

### ISSUE THREAD

**Issue by clockworkgr** [tendermint/vue#91]
https://vitejs.dev/guide/why.html

Seems to be faster and uses rollup instead of webpack.

**Comment by clockworkgr** [comment]
Unfortunately although vite is super cool and speedy, it only works with ESM code. That means that all deps must be ESM modules...protobufjs isn't.

Will keep investigating but I don't think I'll be able to get it to work.

**Comment by marinhoarthur** [comment]
Update on migrating to `vite`:

- `starport/vue` & `starport/vuex` already building with `vite` 

- `starport/client-js` is the last missing piece. I'm really thinking of merging this package into `starport/vuex` and call it a day    😄

**Comment by clockworkgr** [comment]
`starport/client-js` does not need vite as it's not a frontend related piece (technically neither is `starport/vuex` as its used as a library but it originally used webpack as it was vue-related)

You could use a simple rollup or babel config for it. Its only issue at the moment is that it's packaged as a node lib rather than a browser lib

**Comment by marinhoarthur** [comment]
update: 

- will be closed once next major is published
